### ISSUE TITLE
accuracy, typing, and scrolling started freaking out

### ISSUE THREAD

**Issue by CrafterOnVR** [kgsensei/TypingcomHack2#2]
It started spazzing out and the accuracy was god awful and it was spamming random letters. It also kept scrolling down immediately. It was weird.

**Comment by kgsensei** [comment]
Most likely something happened where the program got disoriented or you tried changing something on the page while it was racing. That could cause it to miss a letter, thus causing all subsequent letters to fail. The scrolling down would also be caused by this, ex. try pressing space on a website w/o an input being selected. Closing as invalid unless you provide more context.
